name: playground
services:
  k6-app-go:
    image: docker.io/grafana/k6:latest
    command: run /scenarios/scenario-0.js
    restart: no
    environment:
      - API_HOST=http://app-go-server
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/k6/scenarios:/scenarios

  k6-app-java:
    image: docker.io/grafana/k6:latest
    command: run /scenarios/scenario-0.js
    restart: no
    environment:
      - API_HOST=http://app-java-server
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/k6/scenarios:/scenarios


  k6-broker-enqueue:
    image: docker.io/grafana/k6:latest
    command: run /scenarios/scenario-broker-enqueue.js
    restart: no
    environment:
      - BROKER_HOST=broker:4000
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/k6/scenarios:/scenarios
      - ${LOCAL_WORKSPACE_FOLDER:-.}/broker/broker.proto:/scenarios/broker.proto # to use ./broker's proto
  
  k6-broker-poll-ack:
    image: docker.io/grafana/k6:latest
    command: run /scenarios/scenario-broker-poll-ack.js
    restart: no
    environment:
      - BROKER_HOST=broker:4000
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/k6/scenarios:/scenarios
      - ${LOCAL_WORKSPACE_FOLDER:-.}/broker/broker.proto:/scenarios/broker.proto # to use ./broker's proto
 